version: "3.9"
services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 12345
      MARIADB_DATABASE: booking_db
      MARIADB_USER: Fatma
      MARIADB_PASSWORD: 12345
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
